name             'yum-almalinux'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license          'Apache-2.0'
description      'Installs/Configures AlmaLinux yum repositories'
version          '1.1.6'
source_url       'https://github.com/sous-chefs/yum-almalinux'
issues_url       'https://github.com/sous-chefs/yum-almalinux/issues'
chef_version     '>= 16.10'

supports 'almalinux'
